spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/orders}
    username: ${DB_USER:orders}
    password: ${DB_PASSWORD:orders}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

orders:
  processing:
    cron: "0 */5 * * * *"

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:true}
